#!/usr/bin/env python3
import os
import json
import shutil
from pathlib import Path

def find_root():
    """Find the repository root by looking for .git or common markers."""
    cwd = Path.cwd()
    for path in [cwd] + list(cwd.parents):
        if (path / ".git").exists() or (path / "pyproject.toml").exists() or (path / "package.json").exists():
            return path
    return cwd

def setup_architect():
    root_dir = find_root()
    docs_dir = root_dir / "docs"
    adr_dir = docs_dir / "adr"
    
    # Create directories
    docs_dir.mkdir(exist_ok=True)
    adr_dir.mkdir(exist_ok=True)
    
    # Paths
    arch_doc = docs_dir / "architecture.md"
    ground_rules = docs_dir / "ground-rules.md"
    
    # Template path (relative to this script) - assuming it will be in skills/architecture-design/scripts/
    script_dir = Path(__file__).parent.absolute()
    # If scripts are in skills/architecture-design/scripts/, templates are in ../templates
    template_path = script_dir.parent / "templates" / "arch-template.md"
    
    # Search for template if strict path fails
    if not template_path.exists():
         # Fallback try to find it relative to current dir
         template_path = Path("skills/architecture-design/templates/arch-template.md").absolute()

    # Copy template if destination doesn't exist
    if not arch_doc.exists():
        if template_path.exists():
            shutil.copy(template_path, arch_doc)
        else:
            # Create a basic one if template missing
            arch_doc.write_text("# System Architecture\n\nGenerated by architecture-design skill.")
    
    # Find specifications
    specs_dir = root_dir / "specs"
    feature_specs = []
    if specs_dir.exists():
        feature_specs = [str(p.relative_to(root_dir)) for p in specs_dir.glob("*/spec.md")]
    
    product_name = root_dir.name
    
    # Output JSON
    output = {
        "ARCH_DOC": str(arch_doc.relative_to(root_dir)) if arch_doc.exists() else "",
        "DOCS_DIR": str(docs_dir.relative_to(root_dir)),
        "ADR_DIR": str(adr_dir.relative_to(root_dir)),
        "SPECS_DIR": str(specs_dir.relative_to(root_dir)) if specs_dir.exists() else "",
        "SPEC_COUNT": len(feature_specs),
        "FEATURE_SPECS": feature_specs,
        "PRODUCT_NAME": product_name,
        "GROUND_RULES": str(ground_rules.relative_to(root_dir)) if ground_rules.exists() else ""
    }
    
    print(json.dumps(output, indent=2))

if __name__ == "__main__":
    setup_architect()
